/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './context/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#c6c6cd',
        'on-background': '#0b1c30',
        'error-container': '#ffdad6',
        'inverse-surface': '#213145',
        'surface-container-highest': '#d3e4fe',
        'outline': '#76777d',
        'inverse-primary': '#bec6e0',
        'background': '#f8f9ff',
        'on-surface-variant': '#45464d',
        'primary': '#000000',
        'surface-bright': '#f8f9ff',
        'surface-container-low': '#eff4ff',
        'secondary-fixed': '#dce1ff',
        'secondary-fixed-dim': '#b6c4ff',
        'on-primary-fixed': '#131b2e',
        'tertiary': '#000000',
        'surface-dim': '#cbdbf5',
        'on-secondary-fixed': '#00164e',
        'on-secondary-container': '#1d3989',
        'on-secondary': '#ffffff',
        'primary-container': '#131b2e',
        'surface': '#f8f9ff',
        'surface-variant': '#d3e4fe',
        'on-tertiary-container': '#c76c00',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed-variant': '#6e3900',
        'tertiary-container': '#2f1500',
        'secondary-container': '#8fa7fe',
        'on-primary': '#ffffff',
        'surface-container-high': '#dce9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-error': '#ffffff',
        'surface-tint': '#565e74',
        'on-surface': '#0b1c30',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary-fixed-variant': '#264191',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-primary-container': '#7c839b',
        'error': '#ba1a1a',
        'on-tertiary-fixed': '#2f1500',
        'primary-fixed-dim': '#bec6e0',
        'surface-container-lowest': '#ffffff',
        'secondary': '#4059aa',
        'surface-container': '#e5eeff',
        'primary-fixed': '#dae2fd',
        'on-error-container': '#93000a',
        brand: {
          primary: '#4059aa',
          secondary: '#1d3989',
          accent: '#059669',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'container-max': '80rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease both',
        'pulse-glow': 'pulseGlow 2s ease infinite',
        'spin-slow': 'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 10px rgba(64,89,170,0.3)' },
          '50%': { boxShadow: '0 0 25px rgba(64,89,170,0.6)' },
        },
      },
    },
  },
  plugins: [],
};
